-- v0.6.1
-- Seed intencionalmente vacío.
-- A partir de esta versión no se insertan expedientes ni estrategias demo por defecto.
-- El sistema debe arrancar limpio y abrir expedientes provisionales desde el primer input real.
