export const DOCUMENT_TYPES = {
  DNI_COMPRADOR: 'dni_comprador',
  DNI_VENDEDOR: 'dni_vendedor',
  DNI: 'dni',
  PERMISO_CIRCULACION: 'permiso_circulacion',
  FICHA_TECNICA: 'ficha_tecnica',
  CONTRATO_FACTURA: 'contrato_factura',
  JUSTIFICANTE_PAGO: 'justificante_pago',
  MODELO_620: 'modelo_620',
  MODELO_621: 'modelo_621',
  TASA_DGT_1_5: 'tasa_dgt_1_5',
  TASA_DGT_4_1: 'tasa_dgt_4_1',
  TASA_DGT_4_4: 'tasa_dgt_4_4',
  MANDATO_GESTORIA: 'mandato_gestoria',
  SOLICITUD_BAJA: 'solicitud_baja',
  SOLICITUD_DUPLICADO: 'solicitud_duplicado',
  CERTIFICADO_CAT: 'certificado_cat',
  DOCUMENTACION_EXPORTACION: 'documentacion_exportacion',
  DOCUMENTACION_EXTRANJERA: 'documentacion_extranjera',
  COC_FICHA_REDUCIDA: 'coc_ficha_reducida',
  DUA: 'dua',
  EMPADRONAMIENTO: 'empadronamiento',
  FOTO: 'foto',
  DECLARACION_EXTRAVIO: 'declaracion_extravio',
  JUSTIFICANTE_DOMICILIO: 'justificante_domicilio',
  DOCUMENTO_TRAFICO: 'documento_trafico',
}

export const DOCUMENT_TYPE_LABELS = {
  [DOCUMENT_TYPES.DNI_COMPRADOR]: 'DNI comprador',
  [DOCUMENT_TYPES.DNI_VENDEDOR]: 'DNI vendedor',
  [DOCUMENT_TYPES.DNI]: 'DNI',
  [DOCUMENT_TYPES.PERMISO_CIRCULACION]: 'Permiso de circulación',
  [DOCUMENT_TYPES.FICHA_TECNICA]: 'Ficha técnica',
  [DOCUMENT_TYPES.CONTRATO_FACTURA]: 'Contrato o factura',
  [DOCUMENT_TYPES.JUSTIFICANTE_PAGO]: 'Justificante de pago / tasa',
  [DOCUMENT_TYPES.MODELO_620]: 'Modelo 620',
  [DOCUMENT_TYPES.MODELO_621]: 'Modelo 621',
  [DOCUMENT_TYPES.TASA_DGT_1_5]: 'Tasa DGT 1.5',
  [DOCUMENT_TYPES.TASA_DGT_4_1]: 'Tasa DGT 4.1',
  [DOCUMENT_TYPES.TASA_DGT_4_4]: 'Tasa DGT 4.4',
  [DOCUMENT_TYPES.MANDATO_GESTORIA]: 'Mandato / autorización',
  [DOCUMENT_TYPES.SOLICITUD_BAJA]: 'Solicitud de baja',
  [DOCUMENT_TYPES.SOLICITUD_DUPLICADO]: 'Solicitud de duplicado',
  [DOCUMENT_TYPES.CERTIFICADO_CAT]: 'Certificado CAT',
  [DOCUMENT_TYPES.DOCUMENTACION_EXPORTACION]: 'Documentación de exportación',
  [DOCUMENT_TYPES.DOCUMENTACION_EXTRANJERA]: 'Documentación extranjera',
  [DOCUMENT_TYPES.COC_FICHA_REDUCIDA]: 'COC o ficha reducida',
  [DOCUMENT_TYPES.DUA]: 'DUA',
  [DOCUMENT_TYPES.EMPADRONAMIENTO]: 'Empadronamiento',
  [DOCUMENT_TYPES.FOTO]: 'Foto',
  [DOCUMENT_TYPES.DECLARACION_EXTRAVIO]: 'Declaración de extravío',
  [DOCUMENT_TYPES.JUSTIFICANTE_DOMICILIO]: 'Justificante de domicilio',
  [DOCUMENT_TYPES.DOCUMENTO_TRAFICO]: 'Documento de tráfico genérico',
}
